// Schema definition for Nexora full-stack app
// Each entity maps to a real SQLite table. Types: text, number, float, bool, date
// fk: { table: 'entityKey', display: 'fieldName' } -> renders as a dropdown in the UI

const ENTITIES = {
  companies: {
    table: 'T01_Company',
    label: 'Companies',
    pk: 'T01_PK',
    pkType: 'text',
    displayField: 'T01_01_Company_Name',
    fields: [
      { name: 'T01_01_Company_Name', label: 'Company Name', type: 'text', required: true },
      { name: 'T01_02_Street_Address', label: 'Street Address', type: 'text' },
      { name: 'T02_City_PK', label: 'City', type: 'text', fk: { table: 'cities', display: 'T02_1_City' } },
      { name: 'T01_06_Web_Site', label: 'Web Site', type: 'text' },
      { name: 'T01_07_Switch_Phone', label: 'Switchboard Phone', type: 'text' },
      { name: 'T01_08_Main_Fax', label: 'Main Fax', type: 'text' },
      { name: 'T06_PK', label: 'Association', type: 'text', fk: { table: 'associations', display: 'T06_01_Association' } },
      { name: 'T01_12_Notes', label: 'Notes', type: 'text' },
      { name: 'T01_13_AccNo', label: 'Account No.', type: 'text' },
      { name: 'T01_14_Obsolete', label: 'Obsolete', type: 'bool' },
      { name: 'T01_15_Customer', label: 'Customer', type: 'bool' },
      { name: 'T01_16_Supplier', label: 'Supplier', type: 'bool' },
    ],
  },
  cities: {
    table: 'T02_CityStatePCode',
    label: 'Cities / States / Postcodes',
    pk: 'T02_City_PK',
    pkType: 'text',
    displayField: 'T02_1_City',
    fields: [
      { name: 'T02_1_City', label: 'City', type: 'text' },
      { name: 'T02_2_State', label: 'State', type: 'text' },
      { name: 'T02_3_PCode', label: 'Postcode', type: 'text' },
      { name: 'T02_4_Comments', label: 'Comments', type: 'text' },
    ],
  },
  yourCompany: {
    table: 'T04_Your_Company',
    label: 'Your Company',
    pk: 'T04_PK',
    pkType: 'text',
    displayField: 'T04_01_Your_Company_Name',
    fields: [
      { name: 'T04_01_Your_Company_Name', label: 'Company Name', type: 'text', required: true },
      { name: 'T04_02_Your_Street_Address', label: 'Street Address', type: 'text' },
      { name: 'T02_City_PK', label: 'City', type: 'text', fk: { table: 'cities', display: 'T02_1_City' } },
      { name: 'T04_06_Your_Web_Site', label: 'Web Site', type: 'text' },
      { name: 'T04_07_Your_Switch', label: 'Switchboard Phone', type: 'text' },
      { name: 'T04_08_Your_Fax', label: 'Fax', type: 'text' },
      { name: 'T04_09_Logo', label: 'Company Logo (used on printed documents)', type: 'image' },
    ],
  },
  employees: {
    table: 'T05_Employees',
    label: 'Employees',
    pk: 'T05_Employee_PK',
    pkType: 'text',
    displayField: 'T05_01_Forename',
    fields: [
      { name: 'T05_01_Forename', label: 'Forename', type: 'text' },
      { name: 'T05_02_Surname', label: 'Surname', type: 'text' },
      { name: 'T05_03_Phone', label: 'Phone', type: 'text' },
      { name: 'T05_04_Fax_Number', label: 'Fax', type: 'text' },
      { name: 'T05_06_Email', label: 'Email', type: 'text' },
      { name: 'T04_PK', label: 'Your Company', type: 'text', fk: { table: 'yourCompany', display: 'T04_01_Your_Company_Name' } },
      { name: 'T05_08_Mobile', label: 'Mobile', type: 'text' },
      { name: 'T05_09_Employee_Number', label: 'Employee Number', type: 'text' },
      { name: 'T05_10_Labour_Rate', label: 'Labour Rate', type: 'number' },
      { name: 'T05_11_Obsolete', label: 'Obsolete', type: 'bool' },
      { name: 'T05_12_Title', label: 'Title', type: 'text' },
    ],
  },
  associations: {
    table: 'T06_Association',
    label: 'Associations',
    pk: 'T06_PK',
    pkType: 'text',
    displayField: 'T06_01_Association',
    fields: [
      { name: 'T06_01_Association', label: 'Association', type: 'text' },
    ],
  },
  contacts: {
    table: 'T07_Contacts',
    label: 'Contacts',
    pk: 'T07_PK',
    pkType: 'text',
    displayField: 'T07_01_Forename',
    fields: [
      { name: 'T07_01_Forename', label: 'Forename', type: 'text' },
      { name: 'T07_02_Surname', label: 'Surname', type: 'text' },
      { name: 'T07_03_Phone', label: 'Phone', type: 'text' },
      { name: 'T07_04_Fax_Number', label: 'Fax', type: 'text' },
      { name: 'T07_05_Email', label: 'Email', type: 'text' },
      { name: 'T01_PK', label: 'Company', type: 'text', fk: { table: 'companies', display: 'T01_01_Company_Name' } },
      { name: 'T07_07_Mobile', label: 'Mobile', type: 'text' },
      { name: 'T07_08_Filter_Check', label: 'Filter Check', type: 'bool' },
      { name: 'T07_09_Filter_Two', label: 'Filter Two', type: 'bool' },
      { name: 'T07_10_Filter_Three', label: 'Filter Three', type: 'bool' },
      { name: 'T07_11_Obsolete', label: 'Obsolete', type: 'bool' },
      { name: 'T07_12_Title', label: 'Title', type: 'text' },
    ],
  },
  contactManagement: {
    table: 'T08_Contact_Management',
    label: 'Contact Notes',
    pk: 'T08_PK',
    pkType: 'text',
    displayField: 'T08_02_Contact_Record',
    fields: [
      { name: 'T08_01_Date', label: 'Date', type: 'date' },
      { name: 'T08_02_Contact_Record', label: 'Note', type: 'text' },
      { name: 'T07_PK', label: 'Contact', type: 'text', fk: { table: 'contacts', display: 'T07_01_Forename' } },
    ],
  },
  directory: {
    table: 'T09_Directory',
    label: 'Directory',
    pk: 'T09_Directory_PK',
    pkType: 'text',
    displayField: 'T09_02_Directory_Description',
    fields: [
      { name: 'T09_01_Directory_Number', label: 'Directory Number', type: 'number' },
      { name: 'T09_02_Directory_Description', label: 'Description', type: 'text' },
      { name: 'T09_03_Obsolete', label: 'Obsolete', type: 'bool' },
    ],
  },
  documents: {
    table: 'T10_Documents',
    label: 'Documents',
    pk: 'T10_Document_PK',
    pkType: 'text',
    displayField: 'T10_03_Short_Description',
    fields: [
      { name: 'T10_01_Document_Number', label: 'Document Number', type: 'number' },
      { name: 'T10_02_Alt_Ref_Number', label: 'Alt Ref Number', type: 'text', required: true },
      { name: 'T10_03_Short_Description', label: 'Short Description', type: 'text' },
      { name: 'T10_04_Long Description', label: 'Long Description', type: 'text', required: true },
      { name: 'T09_Directory_PK', label: 'Directory', type: 'text', fk: { table: 'directory', display: 'T09_02_Directory_Description' } },
      { name: 'T10_06_Obsolete', label: 'Obsolete', type: 'bool' },
    ],
  },
  categories: {
    table: 'T12_Category',
    label: 'Item Categories',
    pk: 'T12_Category_PK',
    pkType: 'text',
    displayField: 'T12_01_Category',
    fields: [
      { name: 'T12_01_Category', label: 'Category', type: 'text' },
      { name: 'T12_02_Picture', label: 'Picture', type: 'image' },
    ],
  },
  couriers: {
    table: 'T13_Courier',
    label: 'Couriers',
    pk: 'T13_PK',
    pkType: 'text',
    displayField: 'T13_01_Courier',
    fields: [
      { name: 'T13_01_Courier', label: 'Courier', type: 'text' },
    ],
  },
  salesOrders: {
    table: 'T14_Sales_Orders',
    label: 'Sales Orders',
    pk: 'T14_SO_PK',
    pkType: 'text',
    displayField: 'T14_01_SO_Number',
    fields: [
      { name: 'T14_01_SO_Number', label: 'SO Number', type: 'number' },
      { name: 'T14_02_Enquiry_Date', label: 'Enquiry Date', type: 'date' },
      { name: 'T14_03_Quote_Date', label: 'Quote Date', type: 'date' },
      { name: 'T14_04_Sale_Date', label: 'Sale Date', type: 'date' },
      { name: 'T14_05_Despatch_Date', label: 'Despatch Date', type: 'date' },
      { name: 'T14_06_Invoice_Date', label: 'Invoice Date', type: 'date' },
      { name: 'T14_07_Payment_Due_Date', label: 'Payment Due Date', type: 'date' },
      { name: 'T05_Employee_PK', label: 'Employee', type: 'text', required: true, fk: { table: 'employees', display: 'T05_01_Forename' } },
      { name: 'T07_PK', label: 'Contact', type: 'text', required: true, fk: { table: 'contacts', display: 'T07_01_Forename', filterFlag: 'customer' } },
      { name: 'T13_PK', label: 'Courier', type: 'text', fk: { table: 'couriers', display: 'T13_01_Courier' } },
      { name: 'T14_08_Quote_Lost_Date', label: 'Quote Lost Date', type: 'date' },
      { name: 'T14_09_Forecast_Date', label: 'Forecast Date', type: 'date' },
      { name: 'T14_10_SO_Notes', label: 'Notes', type: 'text' },
      { name: 'T14_11_Cust_PO_Number', label: 'Customer PO Number', type: 'text' },
      { name: 'T14_12_Conn_Note', label: 'Connote', type: 'text' },
      { name: 'T14_13_Payment Received', label: 'Payment Received', type: 'date' },
      { name: 'T14_14_Despatch_Due_Date', label: 'Despatch Due Date', type: 'date' },
      { name: 'T07_PK_SHIPTO', label: 'Ship To Contact', type: 'text', fk: { table: 'contacts', display: 'T07_01_Forename' } },
      { name: 'T21_Project_ID', label: 'Project', type: 'text', fk: { table: 'projects', display: 'T21_01_Project_Notes' } },
      { name: 'T22_Currency_ID', label: 'Currency', type: 'text', required: true, fk: { table: 'currency', display: 'T22_01_Currency' } },
      { name: 'T14_15_Conversion_Rate', label: 'Conversion Rate', type: 'float' },
    ],
  },
  soDetails: {
    table: 'T15_SO_Details',
    label: 'Sales Order Line Items',
    pk: null, // composite key table, no single PK
    pkType: 'text',
    displayField: 'T15_01_Quantity',
    fields: [
      { name: 'T14_SO_PK', label: 'Sales Order', type: 'text', required: true, fk: { table: 'salesOrders', display: 'T14_01_SO_Number' } },
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', required: true, fk: { table: 'items', display: 'T11_03_Short_Description' } },
      { name: 'T15_01_Quantity', label: 'Quantity', type: 'float' },
      { name: 'T15_02_Price', label: 'Price', type: 'float' },
    ],
  },
  purchaseOrders: {
    table: 'T17_Purchase_Orders',
    label: 'Purchase Orders',
    pk: 'T17_PO_PK',
    pkType: 'text',
    displayField: 'T17_01_PO_Number',
    fields: [
      { name: 'T17_01_PO_Number', label: 'PO Number', type: 'number' },
      { name: 'T17_02_PO_Date', label: 'PO Date', type: 'date' },
      { name: 'T17_03_Received_Date', label: 'Received Date', type: 'date' },
      { name: 'T05_Employee_PK', label: 'Employee', type: 'text', required: true, fk: { table: 'employees', display: 'T05_01_Forename' } },
      { name: 'T07_PK', label: 'Contact', type: 'text', required: true, fk: { table: 'contacts', display: 'T07_01_Forename', filterFlag: 'supplier' } },
      { name: 'T13_PK', label: 'Courier', type: 'text', fk: { table: 'couriers', display: 'T13_01_Courier' } },
      { name: 'T17_04_Due_Date', label: 'Due Date', type: 'date' },
      { name: 'T17_05_Notes', label: 'Notes', type: 'text' },
      { name: 'T21_Project_ID', label: 'Project', type: 'text', fk: { table: 'projects', display: 'T21_01_Project_Notes' } },
      { name: 'T17_06_Date_Paid', label: 'Date Paid', type: 'date' },
    ],
  },
  poDetails: {
    table: 'T18_PO_Details',
    label: 'Purchase Order Line Items',
    pk: null,
    pkType: 'text',
    displayField: 'T18_01_Quantity',
    fields: [
      { name: 'T17_PO_PK', label: 'Purchase Order', type: 'text', required: true, fk: { table: 'purchaseOrders', display: 'T17_01_PO_Number' } },
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', required: true, fk: { table: 'items', display: 'T11_03_Short_Description' } },
      { name: 'T18_01_Quantity', label: 'Quantity', type: 'float' },
      { name: 'T18_02_Price', label: 'Price', type: 'float' },
    ],
  },
  quotations: {
    table: 'T20_Quotations',
    label: 'Quotations',
    pk: 'T20_Quotation_ID',
    pkType: 'number',
    displayField: 'T20_01_Quotation',
    fields: [
      { name: 'T20_01_Quotation', label: 'Quotation', type: 'text' },
    ],
  },
  projects: {
    table: 'T21_Projects',
    label: 'Projects',
    pk: 'T21_Project_ID',
    pkType: 'number',
    displayField: 'T21_03_Project_Name',
    fields: [
      { name: 'T21_02_Project_Code', label: 'Project Code', type: 'text', required: true },
      { name: 'T21_03_Project_Name', label: 'Project Name', type: 'text', required: true },
      { name: 'T01_PK', label: 'Customer', type: 'text', required: true, fk: { table: 'companies', display: 'T01_01_Company_Name' } },
      { name: 'T21_01_Project_Notes', label: 'Project Notes', type: 'text' },
    ],
  },
  currency: {
    table: 'T22_Currency',
    label: 'Currencies',
    pk: 'T22_Currency_ID',
    pkType: 'number',
    displayField: 'T22_01_Currency',
    fields: [
      { name: 'T22_01_Currency', label: 'Currency', type: 'text' },
      { name: 'T22_02_Symbol', label: 'Symbol', type: 'text' },
    ],
  },
  stock: {
    table: 'T23_Stock',
    label: 'Stock Movements',
    pk: 'T23_Stock_ID',
    pkType: 'number',
    displayField: 'T23_02_Quantity',
    fields: [
      { name: 'T23_01_Date', label: 'Date', type: 'date' },
      { name: 'T23_02_Quantity', label: 'Quantity', type: 'number' },
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', fk: { table: 'items', display: 'T11_03_Short_Description' } },
    ],
  },
  serialNumbers: {
    table: 'T24_Serial_Numbers',
    label: 'Serial Numbers',
    pk: 'T24_Serial_PK',
    pkType: 'number',
    displayField: 'T24_03_Serial_Number',
    fields: [
      { name: 'T24_03_Serial_Number', label: 'Serial Number', type: 'text', required: true },
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', required: true, fk: { table: 'items', display: 'T11_03_Short_Description' } },
      { name: 'T14_SO_PK', label: 'Shipped On Sales Order', type: 'text', fk: { table: 'salesOrders', display: 'T14_01_SO_Number' } },
      { name: 'T24_01_Date', label: 'Date', type: 'date' },
      { name: 'T24_04_Warranty_Start', label: 'Warranty Start', type: 'date' },
      { name: 'T24_05_Warranty_End', label: 'Warranty End', type: 'date' },
      { name: 'T24_02_Notes', label: 'Notes', type: 'text' },
    ],
  },
  items: {
    table: 'T11_Item_Master',
    label: 'Item Master',
    pk: 'T11_Item_Master_PK',
    pkType: 'text',
    displayField: 'T11_03_Short_Description',
    fields: [
      { name: 'T11_01_Part_Number', label: 'Item Code', type: 'text', required: true },
      { name: 'T11_02_Alt_Part_Number', label: 'Serial Number', type: 'text' },
      { name: 'T11_03_Short_Description', label: 'Item Name', type: 'text' },
      { name: 'T11_04_Long_Description', label: 'Item Description', type: 'text', required: true },
      { name: 'T11_05_Supplier_Part_Number', label: 'Supplier Part Number', type: 'text' },
      { name: 'T11_06_Qty_OH', label: 'Qty On Hand', type: 'number' },
      { name: 'T11_09_List_Price', label: 'List Price', type: 'float' },
      { name: 'T12_Category_PK', label: 'Category', type: 'text', fk: { table: 'categories', display: 'T12_01_Category' } },
      { name: 'T11_10_Trade_Price', label: 'Trade Price', type: 'float' },
      { name: 'T11_11_OEM_Price', label: 'OEM Price', type: 'float' },
      { name: 'T11_12_Obsolete', label: 'Obsolete', type: 'bool' },
      { name: 'T11_53_COST', label: 'Cost', type: 'float' },
      { name: 'T11_54_ReOrderQty', label: 'Re-order Qty', type: 'float' },
      { name: 'T11_55_Photo', label: 'Photo', type: 'image' },
    ],
  },
  itemDocJoin: {
    table: 'T19_Item_Doc_Join',
    label: 'Item ↔ Document Links',
    pk: null,
    pkType: 'text',
    displayField: 'T11_Item_Master_PK',
    fields: [
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', required: true, fk: { table: 'items', display: 'T11_03_Short_Description' } },
      { name: 'T10_Document_PK', label: 'Document', type: 'text', required: true, fk: { table: 'documents', display: 'T10_03_Short_Description' } },
    ],
  },
  stockRequisitions: {
    table: 'T27_Requisition',
    label: 'Stock Requisitions',
    pk: 'T27_Requisition_ID',
    pkType: 'number',
    displayField: 'T27_04_Requesting_Office',
    filter: { field: 'T27_01_Type', value: 'Stock Requisition' },
    fields: [
      { name: 'T27_09_SRF_Number', label: 'SRF Number', type: 'text' },
      { name: 'T14_SO_PK', label: 'Sales Order', type: 'text', required: true, fk: { table: 'salesOrders', display: 'T14_01_SO_Number' } },
      { name: 'T27_04_Requesting_Office', label: 'Requesting Office / Branch', type: 'text', required: true },
      { name: 'T27_03_Requested_By', label: 'Requested By', type: 'text' },
      { name: 'T27_05_Date_Requested', label: 'Date Requested', type: 'date' },
      { name: 'T27_06_Status', label: 'Status', type: 'text' },
      { name: 'T27_10_Reviewed_By', label: 'Reviewed By', type: 'text' },
      { name: 'T27_11_Reviewed_Date', label: 'Reviewed Date', type: 'date' },
      { name: 'T27_12_Approved_By', label: 'Approved By', type: 'text' },
      { name: 'T27_13_Approved_Date', label: 'Approved Date', type: 'date' },
      { name: 'T27_08_Notes', label: 'Notes', type: 'text' },
    ],
  },
  purchaseRequisitions: {
    table: 'T27_Requisition',
    label: 'Purchase Requisitions',
    pk: 'T27_Requisition_ID',
    pkType: 'number',
    displayField: 'T27_04_Requesting_Office',
    filter: { field: 'T27_01_Type', value: 'Purchase Requisition' },
    fields: [
      { name: 'T27_09_SRF_Number', label: 'SRF Number', type: 'text' },
      { name: 'T14_SO_PK', label: 'Sales Order', type: 'text', required: true, fk: { table: 'salesOrders', display: 'T14_01_SO_Number' } },
      { name: 'T27_04_Requesting_Office', label: 'Requesting Office / Branch', type: 'text', required: true },
      { name: 'T27_03_Requested_By', label: 'Requested By', type: 'text' },
      { name: 'T27_05_Date_Requested', label: 'Date Requested', type: 'date' },
      { name: 'T27_06_Status', label: 'Status', type: 'text' },
      { name: 'T27_10_Reviewed_By', label: 'Reviewed By', type: 'text' },
      { name: 'T27_11_Reviewed_Date', label: 'Reviewed Date', type: 'date' },
      { name: 'T27_12_Approved_By', label: 'Approved By', type: 'text' },
      { name: 'T27_13_Approved_Date', label: 'Approved Date', type: 'date' },
      { name: 'T27_08_Notes', label: 'Notes', type: 'text' },
    ],
  },
  users: {
    table: 'T28_Users',
    label: 'User Management',
    pk: 'T28_User_PK',
    pkType: 'text',
    displayField: 'T28_01_Name',
    fields: [
      { name: 'T28_01_Name', label: 'Full Name', type: 'text', required: true },
      { name: 'T28_02_Username', label: 'Username', type: 'text', required: true },
      { name: 'T28_03_Password', label: 'Password', type: 'text' },
      { name: 'T28_04_Department', label: 'Department', type: 'text', required: true },
      { name: 'T28_08_Role', label: 'Workflow Role (Requester / Reviewer / Manager / Logistics)', type: 'text' },
      { name: 'T28_05_Active', label: 'Active', type: 'bool' },
      { name: 'T28_06_Status', label: 'Approval Status', type: 'text' },
      { name: 'T28_07_Allowed_Entities', label: 'Allowed Sections (comma-separated entity keys, blank = full access)', type: 'text' },
    ],
  },
  forecasts: {
    table: 'T26_Forecast',
    label: 'Sales Forecasts',
    pk: 'T26_Forecast_ID',
    pkType: 'number',
    displayField: 'T26_02_Delivery_Month',
    fields: [
      { name: 'T11_Item_Master_PK', label: 'Item', type: 'text', required: true, fk: { table: 'items', display: 'T11_03_Short_Description' } },
      { name: 'T01_PK', label: 'Customer / Branch', type: 'text', fk: { table: 'companies', display: 'T01_01_Company_Name' } },
      { name: 'T26_01_Forecast_Quantity', label: 'Forecast Quantity', type: 'float', required: true },
      { name: 'T26_02_Delivery_Month', label: 'Required Delivery Month', type: 'text', required: true },
      { name: 'T26_04_Quarter', label: 'Quarter (e.g. 2026-Q3)', type: 'text', required: true },
      { name: 'T26_05_Submitted_By', label: 'Submitted By', type: 'text' },
      { name: 'T26_03_Remarks', label: 'Remarks / Special Requirements', type: 'text' },
    ],
  },
  soFulfillment: {
    table: 'T25_SO_Fulfillment',
    label: 'Sales Order Fulfillment',
    pk: 'T14_SO_PK',
    pkType: 'text',
    displayField: 'T25_01_Status',
    fields: [
      { name: 'T25_01_Status', label: 'Status', type: 'text' },
      { name: 'T25_02_StockCheckStatus', label: 'Stock Check Status', type: 'text' },
      { name: 'T25_03_FactoryPO_Ref', label: 'Factory PO Reference', type: 'text' },
      { name: 'T25_04_AllocatedDate', label: 'Allocated Date', type: 'date' },
      { name: 'T25_05_ProformaIssued', label: 'Proforma Issued', type: 'bool' },
      { name: 'T25_06_ProformaDate', label: 'Proforma Date', type: 'date' },
      { name: 'T25_07_AdvancePaymentRequired', label: 'Advance Payment Required', type: 'bool' },
      { name: 'T25_08_AdvancePaymentAmount', label: 'Advance Payment Amount', type: 'float' },
      { name: 'T25_09_AdvancePaymentDate', label: 'Advance Payment Date', type: 'date' },
      { name: 'T25_10_PaymentReceiptIssued', label: 'Payment Receipt Issued', type: 'bool' },
      { name: 'T25_11_HSCode', label: 'HS Code', type: 'text' },
      { name: 'T25_12_Dimensions', label: 'Dimensions', type: 'text' },
      { name: 'T25_13_WeightKg', label: 'Weight (kg)', type: 'float' },
      { name: 'T25_14_PackedDate', label: 'Packed Date', type: 'date' },
      { name: 'T25_15_CommercialInvoiceIssued', label: 'Commercial Invoice Issued', type: 'bool' },
      { name: 'T25_16_PackingListIssued', label: 'Packing List Issued', type: 'bool' },
      { name: 'T25_17_DeliveryNoteIssued', label: 'Delivery Note Issued', type: 'bool' },
      { name: 'T25_18_ShippingArrangedBy', label: 'Shipping Arranged By', type: 'text' },
      { name: 'T25_19_ForwarderName', label: 'Forwarder / Courier Name', type: 'text' },
      { name: 'T25_20_ShippingChargesTo', label: 'Shipping Charges', type: 'text' },
      { name: 'T25_21_TrackingType', label: 'Tracking Type', type: 'text' },
      { name: 'T25_22_TrackingNumber', label: 'Tracking Number', type: 'text' },
      { name: 'T25_23_ShippedDate', label: 'Shipped Date', type: 'date' },
      { name: 'T25_24_DeliveryNoteSigned', label: 'Delivery Note Signed', type: 'bool' },
      { name: 'T25_25_DeliveryConfirmedDate', label: 'Delivery Confirmed Date', type: 'date' },
      { name: 'T25_26_Discrepancies', label: 'Discrepancies / Notes', type: 'text' },
      { name: 'T25_27_Warranty_Duration', label: 'Warranty Duration', type: 'text' },
      { name: 'T25_28_Warranty_Start', label: 'Warranty Start Date', type: 'date' },
      { name: 'T25_29_Warranty_End', label: 'Warranty End Date', type: 'date' },
    ],
  },
};

// Nav grouping for the frontend sidebar
const NAV_GROUPS = [
  { label: 'CRM', entities: ['companies', 'contacts', 'contactManagement', 'employees', 'associations', 'cities', 'yourCompany', 'projects'] },
  { label: 'Sales & Purchasing', entities: ['salesOrders', 'soDetails', 'purchaseOrders', 'poDetails', 'quotations', 'stockRequisitions', 'purchaseRequisitions'] },
  { label: 'Inventory', entities: ['items', 'categories', 'stock', 'serialNumbers', 'forecasts'] },
  { label: 'Documents & Reference', entities: ['documents', 'directory', 'itemDocJoin', 'currency', 'couriers', 'users'] },
];

module.exports = { ENTITIES, NAV_GROUPS };
